#!/bin/sh

# general config

. /etc/conf.d/xcgi
. /etc/rc.conf
. /etc/rc.d/functions

# global varaibles
declare PIDS
FILES=$(find $VHOSTS -name \*\.conf)


case "$1" in
  start)
  stat_busy "Starting CGI Server"
  for file in $FILES
  do
    . $file

    if [ $LANGUAGE = 'python' ] && [ $FLAMEWORK = 'django' ] ; then
      cd $ROOT_DIR
      gunicorn_django settings.py -b $IP:$PORT --debug --daemon
      pidof -s python >> $PIDFILE
    elif [ $LANGUAGE = 'php' ] && [ $FLAMEWORK = 'none' ] ; then
      cgi-fcgi -start -connect $IP:$PORT $PHP_CGI
      pidof -s $PHP_CGI >> $PIDFILE
    else
      echo "Unknow programming language."
      stat_fail
    fi

  done

  if [ -e $PIDFILE ] ; then
    add_daemon xcgi
    stat_done
  else
    stat_fail
  fi
  ;; 
  stop)
  stat_busy "Stopping CGI Server"
  [ -e /var/run/daemons/xcgi ] && [ -e $PIDFILE ]
  PIDS=`cat $PIDFILE`
  for pid in $PIDS
  do
    kill  $pid &> /dev/null
    #killall gunicorn_django
  done

  if [ $? -ne 0 ] ; then
    stat_fail
  else
    rm_daemon xcgi
    rm $PIDFILE
    stat_done
  fi
  ;;
  restart)
  $0 stop
  sleep 1
  $0 start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart|}"  
esac
